changed english to french
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #128
Opened 2022-06-15 15:06 UTC by DangirasH

2022-06-15 15:16 UTC, MATKYU approved these changes

2022-06-15 16:25 UTC, ThibaultFoure requested changes

2022-06-15 16:25 UTC, ThibaultFoure commented on templates/admin_event/_delete_form.html.twig
> +<form method="post" action="{{ path('admin_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cet élément?');">
espace avant le ?

2022-06-16 08:10 UTC, codelande approved these changes

2022-06-16 08:25 UTC, ThibaultFoure approved these changes

2022-06-16 08:25 UTC, merged