Hnc26 admin add member
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #239
Opened 2022-06-21 14:36 UTC by DESCARAVAGE

2022-06-21 14:48 UTC, codelande requested changes

2022-06-21 14:48 UTC, codelande commented on src/Entity/Member.php
> +    #[ORM\GeneratedValue]
il faut les assert dans ton entity pour bien vérifier ton formulaire

2022-06-22 07:01 UTC, codelande approved these changes

2022-06-22 08:32 UTC, ThibaultFoure requested changes

2022-06-22 08:32 UTC, ThibaultFoure commented on src/Entity/Member.php
> +        maxMessage: 'Le titre ne doit pas dépasser {{ limit }} caractères'
tu es sûr que c'est un titre que tu vérifies ?

2022-06-22 08:40 UTC, codelande approved these changes

2022-06-22 08:44 UTC, ThibaultFoure requested changes

2022-06-22 08:44 UTC, ThibaultFoure commented on src/Entity/Member.php
> +        maxMessage: 'Le prenom ne doit pas dépasser {{ limit }} caractères'
prénom

2022-06-22 08:59 UTC, DangirasH approved these changes

2022-06-22 09:04 UTC, ThibaultFoure approved these changes

2022-06-22 09:04 UTC, merged