edit + index Admin member
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #240
Opened 2022-06-21 14:43 UTC by DESCARAVAGE

2022-06-21 14:49 UTC, codelande submitted a review, later dismissed

2022-06-21 14:56 UTC, ThibaultFoure requested changes

2022-06-21 14:56 UTC, ThibaultFoure commented on templates/admin/admin_member/index.html.twig
> +{% block title %}Membre
ssssssssssssssssssssssssssssssssssssss

2022-06-21 14:56 UTC, ThibaultFoure commented on templates/admin/admin_member/index.html.twig
> +					<td colspan="6">pas de membres trouvés</td>
majuscule

2022-06-22 07:02 UTC, codelande approved these changes

2022-06-22 08:23 UTC, ThibaultFoure approved these changes

2022-06-22 08:23 UTC, merged