S03 hnc25 actus del index
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #243
Opened 2022-06-21 15:09 UTC by codelande

2022-06-21 15:13 UTC, DangirasH submitted a review, later dismissed

2022-06-22 08:22 UTC, ThibaultFoure requested changes

2022-06-22 08:22 UTC, ThibaultFoure commented on templates/admin/admin_actuality/index.html.twig
> +						<td colspan="6">Aucun résultats</td>
singulier ou pluriel, il faut faire un choix

2022-06-22 08:40 UTC, DESCARAVAGE submitted a review, later dismissed

2022-06-22 08:48 UTC, ThibaultFoure requested changes

2022-06-22 08:48 UTC, ThibaultFoure commented on templates/admin/admin_actuality/index.html.twig
> +						<td colspan="6">Aucuns résultats</td>
ok mauvais choix du coup, je viens de check, aucun -> "Il est au pluriel lorsqu’il se trouve devant un mot qui est lui-même toujours au pluriel." donc singulier ici

2022-06-22 09:01 UTC, DangirasH submitted a review, later dismissed

2022-06-22 09:06 UTC, ThibaultFoure approved these changes

2022-06-22 09:20 UTC, closed without merging