Admin Crud for Networks
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #272
Opened 2022-06-22 15:17 UTC by DangirasH

2022-06-22 15:29 UTC, DESCARAVAGE requested changes

2022-06-22 15:29 UTC, DESCARAVAGE commented on templates/admin/admin_network/index.html.twig
> +{% block title %}Reseaux sociaux{% endblock %}
é de Resaux

2022-06-22 15:29 UTC, DESCARAVAGE commented on templates/admin/admin_network/index.html.twig
> +    <h1>Reseaux sociaux</h1>
é de resaux

2022-06-22 15:29 UTC, DESCARAVAGE commented on templates/admin/admin_network/index.html.twig
> +                <th>Actions</th>
class="d-flex justify-content-center" pour Action <th>

2022-06-22 15:29 UTC, DESCARAVAGE commented on templates/admin/admin_network/index.html.twig
> +                <td colspan="4">Pas de reseaux sociaux trouvés</td>
é de resaux

2022-06-22 16:27 UTC, DESCARAVAGE approved these changes

2022-06-23 08:46 UTC, ThibaultFoure commented on src/Repository/NetworkRepository.php
> +}
à supprimer

2022-06-23 08:48 UTC, ThibaultFoure commented on templates/admin/admin_network/index.html.twig
> +                <th>Actions</th>
> class="d-flex justify-content-center" pour Action

C'est pas modifié ça ?

2022-06-23 10:07 UTC, merged