Fix form contact entity
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #275
Opened 2022-06-22 15:27 UTC by codelande

2022-06-22 16:26 UTC, DESCARAVAGE approved these changes

2022-06-22 17:40 UTC, ThibaultFoure requested changes
Tu as mis des assert sur ton entité, mais pas de messages d'erreur correspondant, et tant que tu y es, ça peut être l'occasion de scinder le fichier index en déportant le form dans un composant et les réseaux dans un autre, puis de les include, ce sera plus lisible

2022-06-23 07:34 UTC, codelande commented
> Tu as mis des assert sur ton entité, mais pas de messages d'erreur correspondant, et tant que tu y es, ça peut être l'occasion de scinder le fichier index en déportant le form dans un composant et les réseaux dans un autre, puis de les include, ce sera plus lisible

Les messages sont générés automatiquement par symfony, ok pour les components

2022-06-23 07:43 UTC, DangirasH approved these changes

2022-06-23 08:51 UTC, merged