Fix admin home content
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #279
Opened 2022-06-23 09:02 UTC by DangirasH

2022-06-23 09:07 UTC, codelande submitted a review, later dismissed

2022-06-23 10:25 UTC, ThibaultFoure requested changes

2022-06-23 10:25 UTC, ThibaultFoure commented on assets/styles/homeAdmin.scss
> +    font-size: 4rem;
Bootstrap

2022-06-23 10:25 UTC, ThibaultFoure commented on assets/styles/homeAdmin.scss
> +    border-color: $primary;
Bootstrap

2022-06-23 10:25 UTC, ThibaultFoure commented on assets/styles/homeAdmin.scss
> +    justify-content: center;
Bootstrap

2022-06-23 10:25 UTC, ThibaultFoure commented on assets/styles/homeAdmin.scss
> +    background: rgb(23, 23, 23);
à mettre dans une variable

2022-06-23 10:25 UTC, ThibaultFoure commented on assets/styles/homeAdmin.scss
> +        rgba(255, 255, 255, 1) 50.1%,
pourquoi 50.1 ?

2022-06-23 10:25 UTC, ThibaultFoure commented on assets/styles/homeAdmin.scss
> +    width: 100%;
Bootstrap

2022-06-23 10:25 UTC, ThibaultFoure commented on templates/admin/admin_home/index.html.twig
> +		<div class="Card container mb-5">
Card n'est pas explicite comme nom de classe, en plus c'est une classe bootstrap (sans majuscule) donc ça prête à confusion
+ La classe container est faite pour se trouver au dessus des sections, rows etc, tu ne dois pas en avoir plusieurs sur la page

2022-06-23 10:25 UTC, ThibaultFoure commented on templates/admin/admin_home/index.html.twig
> +	<section class="d-flex flex-row">
de base le d-flex est en row, flex-row ne sert à rien, utilise la classe row c'est plus adapté

2022-06-23 10:25 UTC, ThibaultFoure commented on templates/admin/admin_home/index.html.twig
> +					<h3 class="m-5">Actualites</h3>
pareil pour tes autres cards du coup

2022-06-27 08:15 UTC, DangirasH commented on assets/styles/homeAdmin.scss
> +        rgba(255, 255, 255, 1) 50.1%,
pour faire que la Split ligne est smooth est pas rigureux

2022-06-28 06:59 UTC, codelande requested changes
il faut faire un gitignore pour les images uploadés

2022-06-28 13:32 UTC, codelande submitted a review, later dismissed

2022-06-28 14:48 UTC, MATKYU submitted a review, later dismissed

2022-06-28 15:02 UTC, ThibaultFoure approved these changes

2022-07-04 08:15 UTC, merged