harmonisation du style admin
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #292
Opened 2022-06-23 14:22 UTC by codelande

2022-06-23 14:54 UTC, MATKYU submitted a review, later dismissed

2022-06-23 15:13 UTC, ThibaultFoure requested changes

2022-06-23 15:13 UTC, ThibaultFoure commented on templates/admin/admin_member/_form.html.twig
> +		<button class="btn btn-secondary">{{ button_label|default('Ajouter') }}<i class="ms-1 bi bi-check-lg"></i></button></button>
2 balises button fermantes

2022-06-27 07:35 UTC, MATKYU approved these changes

2022-06-27 07:49 UTC, ThibaultFoure approved these changes

2022-06-27 07:49 UTC, merged