S01 hnc09 contact form
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #31
Opened 2022-06-08 10:34 UTC by codelande

2022-06-08 12:08 UTC, DESCARAVAGE approved these changes

2022-06-08 13:58 UTC, ThibaultFoure requested changes
100 ko max les images

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/base.html.twig
> +		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
à supprimer

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
pourquoi

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
tant

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
de

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
lignes

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
vides

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
dans

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
ce

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
fichier

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
de

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
vue

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/_email.html.twig
> +
?

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/index.html.twig
> +{% block title %}Contact
si tu passes une variable title dans ton controller, réutilise là

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/index.html.twig
> +	<h3 class="text-center">"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</h3>
bof bof le lorem, si vraiment vous avez rien vous pouvez, mais là essayez de mettre un petit texte même fictif, surtout que pour un h3 ça me parait long

2022-06-08 13:58 UTC, ThibaultFoure commented on templates/contact/index.html.twig
> +				{% for message in app.flashes('success') %}
idéalement, l'affichage des messages flash est à placer dans base, ça évitera que vous répétiez ce code à chaque endroit où vous aurez besoin

2022-06-08 14:40 UTC, codelande commented on templates/contact/index.html.twig
> +{% block title %}Contact
c pour plus tard

2022-06-08 14:46 UTC, codelande commented on templates/contact/index.html.twig
> +				{% for message in app.flashes('success') %}
pour linstant j retouche pas on reverra ensemble je pense

2022-06-08 14:50 UTC, MATKYU submitted a review, later dismissed

2022-06-09 08:33 UTC, ThibaultFoure requested changes

2022-06-09 08:33 UTC, ThibaultFoure commented on src/Controller/ContactController.php
> +            return $this->redirectToRoute('app_contact');
la route

2022-06-09 09:47 UTC, MATKYU approved these changes

2022-06-09 09:54 UTC, ThibaultFoure requested changes

2022-06-09 09:54 UTC, ThibaultFoure commented on templates/contact/index.html.twig
> +	<h3 class="text-center">"Nous somme à votre écoute"</h3>
sommeS

2022-06-09 10:26 UTC, codelande commented on templates/contact/index.html.twig
> +	<h3 class="text-center">"Nous somme à votre écoute"</h3>
pitié mr

2022-06-09 10:27 UTC, MATKYU submitted a review, later dismissed

2022-06-09 11:58 UTC, ThibaultFoure approved these changes

2022-06-09 14:17 UTC, merged