S04HNC51_Event_passé_futur
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #326
Opened 2022-06-27 13:28 UTC by DESCARAVAGE

2022-06-27 13:31 UTC, MATKYU requested changes

2022-06-27 13:31 UTC, MATKYU commented on templates/event/index.html.twig
> +			{% else %}
...

2022-06-27 13:31 UTC, MATKYU commented on templates/event/index.html.twig
> +			{% else %}
...

2022-06-27 15:05 UTC, codelande requested changes
ajoute un gitignore pour l'upload de tes images

2022-06-28 09:58 UTC, codelande approved these changes
gg

2022-06-28 13:37 UTC, codelande submitted a review, later dismissed

2022-06-28 14:26 UTC, ThibaultFoure approved these changes

2022-07-04 08:16 UTC, merged