S04HNC54_Style_Partenaire
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #336
Opened 2022-06-28 10:24 UTC by MATKYU

2022-06-28 13:32 UTC, codelande approved these changes

2022-07-04 07:32 UTC, ThibaultFoure requested changes

2022-07-04 07:32 UTC, ThibaultFoure commented on assets/styles/partners.scss
> +}
pas de code commenté

2022-07-04 07:36 UTC, codelande submitted a review, later dismissed

2022-07-04 08:57 UTC, ThibaultFoure requested changes
ajoute une .gitignore dans ton dossier /uploads/partners

2022-07-04 14:59 UTC, DangirasH requested changes
upload files not gitignored

2022-07-04 15:02 UTC, DangirasH approved these changes

2022-07-04 15:14 UTC, ThibaultFoure submitted a review, later dismissed

2022-07-04 16:33 UTC, merged