S01 hnc02 footer
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #34
Opened 2022-06-08 14:25 UTC by MATKYU

2022-06-08 14:38 UTC, codelande requested changes

2022-06-08 14:48 UTC, codelande approved these changes

2022-06-09 09:27 UTC, ThibaultFoure approved these changes

2022-06-09 09:27 UTC, ThibaultFoure commented on templates/_footer.html.twig
> +						<li class="list-unstyled">Adress Email : <a class="text-secondary" href="#">contact.splitscreen@gmail.com</a></li>
adressE

2022-06-09 09:44 UTC, MATKYU commented on templates/_footer.html.twig
> +						<li class="list-unstyled">Adress Email : <a class="text-secondary" href="#">contact.splitscreen@gmail.com</a></li>
PardonE

2022-06-09 09:50 UTC, codelande submitted a review, later dismissed

2022-06-09 09:55 UTC, ThibaultFoure approved these changes

2022-06-09 14:17 UTC, merged