S05HNC46_Tournament
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #361
Opened 2022-07-04 14:53 UTC by MATKYU

2022-07-04 14:57 UTC, DangirasH submitted a review, later dismissed

2022-07-05 09:38 UTC, ThibaultFoure requested changes

2022-07-05 09:38 UTC, ThibaultFoure commented on src/Repository/ParticipantRepository.php
> +}
Code commenté à supprimer

2022-07-05 09:38 UTC, ThibaultFoure commented on src/DataFixtures/ParticipantFixtures.php
> +            $user->setEvent($this->getReference('event0'));
utilise plutot la référence qui est générée dans tes fixtures event

2022-07-05 14:09 UTC, DangirasH submitted a review, later dismissed

2022-07-05 14:13 UTC, ThibaultFoure approved these changes

2022-07-05 14:19 UTC, merged