imgCards
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #373
Opened 2022-07-05 14:17 UTC by DESCARAVAGE

2022-07-05 14:19 UTC, DangirasH submitted a review, later dismissed

2022-07-05 15:13 UTC, ThibaultFoure requested changes

2022-07-05 15:13 UTC, ThibaultFoure commented on templates/home/index.html.twig
> +								<img src="{{ vich_uploader_asset(event) }}" alt="photographie mise en avant" class="imgCards card-img-top">
pareil ici, reprendre le titre dans le alt

2022-07-05 15:13 UTC, ThibaultFoure commented on templates/home/index.html.twig
> +								<img src="{{ asset('build/images/' ~ actu.image) }}" alt="photographie mise en avant" class="imgCards card-img-top">
et ici aussi

2022-07-06 09:45 UTC, DangirasH approved these changes

2022-07-06 10:16 UTC, ThibaultFoure approved these changes

2022-07-06 10:16 UTC, merged