m
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #397
Opened 2022-07-06 12:34 UTC by codelande

2022-07-06 13:39 UTC, DangirasH requested changes

2022-07-06 13:39 UTC, DangirasH commented on templates/components/_members.html.twig
> +			{% endif %}
"à" afficher

2022-07-06 13:39 UTC, DangirasH submitted a review, later dismissed

2022-07-06 14:49 UTC, DangirasH submitted a review, later dismissed

2022-07-06 14:58 UTC, ThibaultFoure requested changes

2022-07-06 14:58 UTC, ThibaultFoure commented on templates/components/_members.html.twig
> +						<img src="{{ asset('uploads/member/' ~ member.image) }}" class=" w-100 partner-image"/>
le alt ?

2022-07-07 10:19 UTC, ThibaultFoure approved these changes

2022-07-07 10:19 UTC, merged