S01 hnc5 structure asso
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #40
Opened 2022-06-09 10:06 UTC by DangirasH

2022-06-09 10:18 UTC, DESCARAVAGE commented on templates/association/index.html.twig
> +				Qui Sommes Nous ?
Des maj à chaque lettre ?

2022-06-09 10:19 UTC, DESCARAVAGE requested changes

2022-06-09 10:19 UTC, DESCARAVAGE commented on assets/styles/app.scss
> +h2 {
il faudrait peut être ouvrir une feuille scss pour modifier ta page en question sinon tous les H2 seront modifiés

2022-06-09 14:13 UTC, DESCARAVAGE submitted a review, later dismissed
À toi de jouer !!!

2022-06-10 07:27 UTC, ThibaultFoure requested changes
100 ko max les images

2022-06-10 07:27 UTC, ThibaultFoure commented on assets/styles/app.scss
> +
ne touche pas aux fichiers que tu ne modifies pas, ils ne doivent pas être dans ta PR

2022-06-10 07:27 UTC, ThibaultFoure commented on assets/styles/association.scss
> +    padding: 10px;
essaie de faire les padding avec bootstrap plutot

2022-06-10 07:27 UTC, ThibaultFoure commented on src/Controller/AssociationController.php
> +    #[Route('/association', name: 'app_association')]
enlève le app dans le nom de ta route

2022-06-10 07:27 UTC, ThibaultFoure commented on templates/association/index.html.twig
> +				L'association Split Screen une association loi 1901 basée à Orléans, dont l'objet est de promouvoir et développer la culture vidéoludique.
L'association Split Screen EST une

2022-06-10 07:27 UTC, ThibaultFoure commented on templates/association/index.html.twig
> +{% block title %}Hello AssociationController!
titre à changer

2022-06-10 07:27 UTC, ThibaultFoure commented on src/Controller/AssociationController.php
> +            'controller_name' => 'AssociationController',
à quoi sert cette variable ? Elle n'est pas utilisée

2022-06-10 09:34 UTC, codelande approved these changes

2022-06-10 14:07 UTC, ThibaultFoure requested changes

2022-06-12 07:58 UTC, DESCARAVAGE requested changes

2022-06-12 07:58 UTC, DESCARAVAGE commented on templates/association/index.html.twig
> +				L'association Split Screen est une association loi 1901 basée à Orléans, dont l'objet est de promouvoir et développer la culture vidéoludique.<br><br>Fondée en 2019, l'association souhaite permet
attention à la lisibilité il y a beaucoup de caractère sur la même ligne un retour à la ligne serait mieux je regarde si on peut utiliser autre chose que les "<#br#>" pour faire un saut de ligne .

2022-06-12 07:58 UTC, DESCARAVAGE commented on templates/association/index.html.twig
> +						Réunir les joueurs et communautés de joueurs dispersés sur tout le territoireorléanais grâce à des événements etmanifestations organisées tout au long del'année
"territoireorléanais" & "etmanifestation" & "organisées" ne prend de S le masculin l'emporte sur le féminin ça s'écrira organisés.

2022-06-12 07:58 UTC, DESCARAVAGE commented on templates/association/index.html.twig
> +				L'association Split Screen est une association loi 1901 basée à Orléans, dont l'objet est de promouvoir et développer la culture vidéoludique.<br><br>Fondée en 2019, l'association souhaite permet
"vidéoludique" & "dujeu"

2022-06-12 22:19 UTC, DangirasH commented on templates/association/index.html.twig
> +				L'association Split Screen est une association loi 1901 basée à Orléans, dont l'objet est de promouvoir et développer la culture vidéoludique.<br><br>Fondée en 2019, l'association souhaite permet
les br c'etait l'idee di Thibault

2022-06-13 07:42 UTC, DESCARAVAGE approved these changes

2022-06-13 08:24 UTC, ThibaultFoure requested changes
Pourquoi un ajout de 2 lignes vides sur le fichier webpack ?
![brooklyn-nine-nine-terry-jeffords](https://user-images.githubusercontent.com/79161810/173311336-f333f577-481c-4555-a195-3ca3e08fbbf7.gif)

2022-06-13 08:49 UTC, MATKYU approved these changes

2022-06-13 08:56 UTC, ThibaultFoure approved these changes

2022-06-13 09:21 UTC, merged