fix de l'orthographe
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #532
Opened 2022-07-25 09:19 UTC by DESCARAVAGE

2022-07-25 09:27 UTC, DangirasH submitted a review, later dismissed

2022-07-25 09:27 UTC, codelande submitted a review, later dismissed

2022-07-25 10:20 UTC, ThibaultFoure requested changes

2022-07-25 10:20 UTC, ThibaultFoure commented on templates/association/index.html.twig
> +						Réunir les joueurs et solidariser la communautés dispersés sur toute la zone orléanaise grâce à des événements et manifestations organisés tout au long de l'année.
![letter-s](https://user-images.githubusercontent.com/79161810/180754597-91ae0705-1c80-4a7d-ab11-dfd9a79ecaee.gif)

2022-07-25 13:38 UTC, ThibaultFoure requested changes

2022-07-25 13:38 UTC, ThibaultFoure commented on templates/association/index.html.twig
> +						Réunir les joueurs et solidariser la communauté dispersés sur toute la zone orléanaise grâce à des événements et manifestations organisés tout au long de l'année.
alors j'ai déjà refusé à cause de l'orthographe, maintenant je relis la phrase en entier et ça va pas en fait, "la communauté dispersés"

2022-07-27 09:45 UTC, codelande submitted a review, later dismissed

2022-07-27 10:13 UTC, ThibaultFoure requested changes

2022-07-27 10:13 UTC, ThibaultFoure commented on templates/association/index.html.twig
> +						Réunir les joueurs et solidariser la communauté dispersé sur toute la zone orléanaise grâce à des événements et manifestations organisés tout au long de l'année.
communauté disperséE

2022-07-27 10:21 UTC, DangirasH submitted a review, later dismissed

2022-07-27 10:29 UTC, ThibaultFoure approved these changes

2022-07-27 13:04 UTC, ThibaultFoure approved these changes

2022-07-27 13:04 UTC, merged