S02 us33 admin acceuil
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #88
Opened 2022-06-13 10:08 UTC by DangirasH

2022-06-13 10:11 UTC, codelande requested changes

2022-06-13 10:11 UTC, codelande commented on src/Controller/AdminHomeController.php
> +            'controller_name' => 'AdminHomeController',
eneleve moi ca !

2022-06-13 10:11 UTC, codelande commented on templates/_headerImg.html.twig
> +
pk tu enlève le title ?????

2022-06-13 10:11 UTC, codelande commented on templates/admin/admin_home/index.html.twig
> +{% block title %}Hello AdminHomeController!{% endblock %}
Tu es sur pour le titre de la page ??????

2022-06-13 10:16 UTC, codelande submitted a review, later dismissed

2022-06-13 12:24 UTC, ThibaultFoure requested changes

2022-06-13 12:24 UTC, ThibaultFoure commented on templates/admin/_navbarAdmin.html.twig
> +		<a class="navbar-brand" href="/">
utilise le path twig pour le href

2022-06-13 12:24 UTC, ThibaultFoure commented on templates/admin/_navbarAdmin.html.twig
> +					<a class="nav-link text-light" aria-current="page" href="/">Accueil</a>
pareil ici pour le href

2022-06-13 12:24 UTC, ThibaultFoure commented on templates/admin/_navbarAdmin.html.twig
> +					<a class="nav-link text-light" href="#">Evenements</a>
les accents

2022-06-13 12:24 UTC, ThibaultFoure commented on templates/admin/_navbarAdmin.html.twig
> +					<a class="nav-link text-light" href="#">Actu</a>
Il n'y aura qu'une seule actu administrable ?

2022-06-13 12:24 UTC, ThibaultFoure commented on templates/admin/_navbarAdmin.html.twig
> +					<a class="nav-link text-light" href="#">Resultats</a>
accent

2022-06-13 12:24 UTC, ThibaultFoure commented on templates/admin/admin_home/index.html.twig
> +	<h2 class="text-center">Welcome to your gaming editing</h2>
![tenor](https://user-images.githubusercontent.com/79161810/173352879-75bb7fd1-345a-4c3e-bc70-e8470b11c4ef.gif)

2022-06-13 13:47 UTC, DangirasH commented on src/Controller/AdminHomeController.php
> +    #[Route('/admin/home', name: 'app_admin_home')]
??????????????????

2022-06-13 13:53 UTC, DangirasH commented on templates/admin/_navbarAdmin.html.twig
> +		<a class="navbar-brand" href="/">
pk pour le navbar classic on n'utilisé pas le path twig pour les hrefs?

2022-06-13 15:05 UTC, codelande requested changes

2022-06-13 15:21 UTC, codelande submitted a review, later dismissed

2022-06-13 21:22 UTC, ThibaultFoure requested changes

2022-06-13 21:22 UTC, ThibaultFoure commented on src/Controller/AdminHomeController.php
> +    #[Route('/admin/acceuil', name: 'admin_home')]
accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil accueil

2022-06-13 21:22 UTC, ThibaultFoure commented on templates/admin/_navbarAdmin.html.twig
> +		<a class="navbar-brand" href="/">
parce que quand elle a été faite vous n'aviez pas encore de page accueil, ça se fixera au fur et à mesure, mais autant le faire tout de suite ça vous évitera de repasser dessus trop de fois

2022-06-13 21:22 UTC, ThibaultFoure commented on templates/admin/_navbarAdmin.html.twig
> +					<a class="nav-link text-light" aria-current="page" href="/admin/acceuil">Accueil</a>
path twig (accueil)

2022-06-13 21:22 UTC, ThibaultFoure commented on templates/admin/admin_home/index.html.twig
> +
lignes vides à supprimer

2022-06-13 21:22 UTC, ThibaultFoure commented on templates/admin/admin_home/index.html.twig
> +	<h2 class="text-center">Bienvenue dans votre édition de jeux</h2>
peut-être mettre un texte plus général, on n'édite pas que des jeux dans la partie admin ?

2022-06-14 13:44 UTC, codelande requested changes

2022-06-14 13:44 UTC, codelande commented on src/Controller/AdminHomeController.php
> +    #[Route('/admin/accueil ', name: 'admin_home')]
espace après accueil

2022-06-14 13:44 UTC, codelande commented on templates/admin/_navbarAdmin.html.twig
> +					<a class="nav-link text-light" aria-current="page" href="/admin/accueil ">Accueil </a>
plutot utiliser path pas la route en dur ?

2022-06-14 14:26 UTC, codelande submitted a review, later dismissed

2022-06-14 14:33 UTC, DESCARAVAGE approved these changes

2022-06-14 14:33 UTC, DESCARAVAGE commented on src/Controller/AdminHomeController.php
> +        return $this->render('admin/admin_home/index.html.twig', []);
pourquoi créer un tableau vide ?

2022-06-14 14:39 UTC, DESCARAVAGE submitted a review, later dismissed

2022-06-15 08:15 UTC, DESCARAVAGE approved these changes

2022-06-15 08:23 UTC, ThibaultFoure approved these changes

2022-06-15 08:24 UTC, merged