So02 us20 add events
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #97
Opened 2022-06-14 10:30 UTC by DangirasH

2022-06-14 13:54 UTC, codelande requested changes

2022-06-14 13:54 UTC, codelande commented on config/packages/twig.yaml
> +    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
pas sur que tu dois mettre ca la peut etre plutot sur la page ou ce trouve ton form

2022-06-14 13:54 UTC, codelande commented on src/Controller/AdminEventController.php
> +    #[Route('/', name: 'app_admin_event_index', methods: ['GET'])]
pourquoi encore ce APP ?

2022-06-14 13:54 UTC, codelande commented on src/Controller/AdminEventController.php
> +#[Route('/admin/evenements')]
utilise un name pour ta classe a la place de reepeter a chaque méthode

2022-06-14 13:54 UTC, codelande commented on src/Entity/Event.php
> +    #[Assert\NotBlank(message: 'Ce champ ne devra pas etre vide!')]
Plutot: "ce champ ne peut pas etre vide"

2022-06-14 13:54 UTC, codelande commented on src/Form/EventType.php
> +            ->add('image', TextType::class, [
a revoir avec le livecoding de sylvain pour ajouter une image

2022-06-14 13:54 UTC, codelande commented on templates/admin_event/edit.html.twig
> +{% block title %}Edit Event{% endblock %}
plutot ecrire en francais pour le modo

edit->modifier
back to list-> retour a la liste etc...

2022-06-14 13:54 UTC, codelande commented on templates/admin_event/index.html.twig
> +                <th>Title</th>
pariel plutot du francais sur la page

2022-06-14 14:15 UTC, DangirasH commented on config/packages/twig.yaml
> +    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
a voir avec Thib car sinon bootstrap ca fonctionne pas dans la meme facon avec les forms du CRUD

2022-06-14 14:27 UTC, DangirasH commented on src/Form/EventType.php
> +            ->add('image', TextType::class, [
t'attendra la semaine pro alors

2022-06-14 14:56 UTC, codelande submitted a review, later dismissed

2022-06-14 17:47 UTC, ThibaultFoure requested changes
pourquoi cette PR est en reviewed ? aucun des changements que Corentin a demandé n'ont été faits

2022-06-15 08:18 UTC, codelande approved these changes

2022-06-15 08:29 UTC, DESCARAVAGE requested changes

2022-06-15 08:29 UTC, DESCARAVAGE commented on templates/admin_event/index.html.twig
> +                <td colspan="6">no records found</td>
FR

2022-06-15 08:29 UTC, DESCARAVAGE commented on templates/admin_event/index.html.twig
> +    <a href="{{ path('admin_event_new') }}">Create new</a>
FR

2022-06-15 08:29 UTC, DESCARAVAGE commented on templates/admin_event/new.html.twig
> +{% block title %}New Event
FR

2022-06-15 08:29 UTC, DESCARAVAGE commented on templates/admin_event/new.html.twig
> +				<a type="button" class=" btn btn-primary btn-lg m-2" href="{{ path('admin_event_index') }}">back to list</a>
FR

2022-06-15 08:29 UTC, DESCARAVAGE commented on templates/admin_event/show.html.twig
> +{% block title %}Èvénements{% endblock %}
attention l'accent pas dans le bon sens " É "

2022-06-15 12:07 UTC, ThibaultFoure commented on templates/admin_event/edit.html.twig
> +{% extends 'base.html.twig' %}
tu ne dois pas toucher à ce fichier, ta PR ne concerne que le add d'un event

2022-06-15 12:34 UTC, DangirasH commented on templates/admin_event/_delete_form.html.twig
> +<form method="post" action="{{ path('admin_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
je le fera dans la US delete

2022-06-15 12:45 UTC, codelande approved these changes

2022-06-15 12:45 UTC, codelande submitted a review, later dismissed

2022-06-15 14:14 UTC, merged