Fix : Date évènement
WildCodeSchool/2022-03-php-orleans-project-splitscreen pull request #99
Opened 2022-06-14 14:25 UTC by DESCARAVAGE

2022-06-14 14:25 UTC, codelande submitted a review, later dismissed

2022-06-14 17:34 UTC, ThibaultFoure requested changes

2022-06-14 17:34 UTC, ThibaultFoure commented on migrations/Version20220614142018.php
> +final class Version20220614142018 extends AbstractMigration
Pourquoi avoir supprimé et refait une migration si ta structure de bdd ne change pas ?

2022-06-14 17:34 UTC, ThibaultFoure commented on src/DataFixtures/EventFixtures.php
> +            $event->setDate(new DateTime('15-06-2022 16:15'));
utilise plutot faker pour générer des dates aléatoires, sinon vous ne verrez pas si vos tris par date fonctionnent sur les actus etc

2022-06-15 07:36 UTC, DESCARAVAGE commented on migrations/Version20220614142018.php
> +final class Version20220614142018 extends AbstractMigration
ouais my bad je pensais que quand on fesait un " d:f:l " la database était modifiée

2022-06-15 07:58 UTC, DangirasH approved these changes

2022-06-15 10:27 UTC, ThibaultFoure approved these changes

2022-06-15 10:27 UTC, merged